### PR TITLE
Implement some of the functions in Helpers.c with OpenSSL 3.0 APIs (part 1)

### PR DESCRIPTION
**Pull request by stefanberger**
Implement some of the functions in Helpers.c with OpenSSL 3.0 APIs.

### CODE REVIEW

**Comment by stefanberger** [comment]
@elmarco I think the abstractions here are good now for supporting OpenSSL 3.0 and the older versions via the new function BuildRSAKey(), but in terms of performance this needs a lot more memory allocations for duplicating BIGNUMs now (in the OpenSSL 1.x version of BuildRSAKey()) than before with only OpenSSL 1.x support. 

I think this is for 'after libtpms v0.9.0'.

**Comment by elmarco** [comment]
@stefanberger I am not that familiar with openssl, but from a 10000ft view, looks ok. Why do you have those `while (1)`? (also in tree already). It should simply abort().

**Comment by stefanberger** [comment]
> Why do you have those `while (1)`? (also in tree already). It should simply abort().

Those are only in test code so I can still hook a debugger onto it and inspect variables if that ends up being helpful at all...

**Comment by elmarco** [comment]
> > Why do you have those `while (1)`? (also in tree already). It should simply abort().
> 
> Those are only in test code so I can still hook a debugger onto it and inspect variables if that ends up being helpful at all...

I see, well abort() should give you a similar result, with `coredumpctl debug`

**Comment by stefanberger** [comment]
Closing this PR now and will merge PR #269 instead.

**Pull request closed without merging**
