### PR TITLE
Remove #define printf

### PR DESCRIPTION
**Pull request by elmarco**
Mass replace printf() occurences with TPMLIB_LogPrintf().

Fixes: #317

Related to:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=46483

### CODE REVIEW

**Comment by stefanberger** [comment]
Thanks for the PR. I wonder whether a backport-able easy patch wouldn't just be

```
#ifdef printf
#undef printf
#endif
```

I would apply this one first before yours...

**Comment by elmarco** [comment]
As long as nothing is using the actual system printf(), that should work. But that could have surprise consequences. I think we should really not #redefine system/lib macros...

**Comment by stefanberger** [comment]
> As long as nothing is using the actual system printf(), that should work. But that could have surprise consequences. I think we should really not #redefine system/lib macros...

Correct. 

My logic here is that we had #define'd printf now for such a long time that this seems to be the simplest fix.

**Comment by elmarco** [comment]
> My logic here is that we had #define'd printf now for such a long time that this seems to be the simplest fix.

My point is that this is not really a fix if you still replace the system printf(). OSS-Fuzz might be redirecting it to some extra checks, fuzzing hint, services etc.

**Comment by stefanberger** [comment]
If you want this to be merged, you would have to rebase the series.

**Comment by stefanberger** [comment]
Series seems stale.

**Pull request closed without merging**
