### PR TITLE
Basic command fuzzing

### PR DESCRIPTION
**Pull request by elmarco**
Add fuzzing test, see README

### CODE REVIEW

**Comment by stefanberger** [comment]
I cherry-picked the tpm12 patch and 'build-sys: remove generated files' for the master branch.

**Comment by elmarco** [comment]
something went wrong with the PR, as I specificied your tpm2 branch. But anyway, you got that ;)

**Comment by stefanberger** [comment]
I keep on cherry-picking...

**Comment by stefanberger** [comment]
I have to use the following command line on Fedora 27 to compile with the fuzzer:

```
CFLAGS="-lasan -lubsan" ./configure --with-openssl --with-tpm2 --enable-sanitizers --enable-fuzzer CC=clang
```

Tough in the end I still get some undefined reference when trying to run `make check`:

```
make[2]: Entering directory '/home/stefanb/tmp/libtpms/src'
There are undefined symbols in libtpms (   )
./.libs/libtpms.so: undefined reference to `__ubsan_handle_pointer_overflow'
./.libs/libtpms.so: undefined reference to `__ubsan_handle_type_mismatch_v1'
make[2]: *** [Makefile:2919: check-local] Error 1
```

How do you get it to run?

**Comment by elmarco** [comment]
did you read the README? :-)

**Comment by elmarco** [comment]
most lilkely in your case, the CFLAGS are wrong. You should be using -fsanitize= in both CFLAGS & LDFLAGS. Then that should compile & link correctly.

**Comment by stefanberger** [comment]
When I follow your steps I end up running into this problem:

```
[stefanb@sbct-3 libtpms]$ make -C tests fuzz
make: Entering directory '/home/stefanb/tmp/libtpms/tests'
/bin/sh ../libtool  --tag=CC   --mode=link clang -fsanitize=fuzzer -g -O2 -Wall -Werror -Wreturn-type -Wsign-compare -Wno-self-assign -fsanitize=fuzzer -ltpms -L../src/.libs -fsanitize=address,undefined  -o fuzz fuzz-fuzz.o  -lcrypto 
libtool: link: clang -fsanitize=fuzzer -g -O2 -Wall -Werror -Wreturn-type -Wsign-compare -Wno-self-assign -fsanitize=fuzzer -fsanitize=address,undefined -o .libs/fuzz fuzz-fuzz.o  /home/stefanb/tmp/libtpms/src/.libs/libtpms.so -L../src/.libs -lcrypto -Wl,-rpath -Wl,/usr/local/lib
/usr/bin/ld: cannot find /usr/lib/libLLVMFuzzer.a: No such file or directory
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
```

Which package has /usr/lib/libLLVMFuzzer.a?

**Comment by elmarco** [comment]
It doesn't exist in f28.. probably a package bug in f27

**Comment by stefanberger** [comment]
I tried it on Fedora 27...

**Comment by stefanberger** [comment]
All merged now.

**Pull request closed without merging**
